//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppImageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppImageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Resources.Strings.AppImageStrings", typeof(AppImageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrow_right_g.png.
        /// </summary>
        internal static string Image_Arrow_Right_Gray {
            get {
                return ResourceManager.GetString("Image_Arrow_Right_Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arrow_right_w.png.
        /// </summary>
        internal static string Image_Arrow_Right_White {
            get {
                return ResourceManager.GetString("Image_Arrow_Right_White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back_b.png.
        /// </summary>
        internal static string Image_Back {
            get {
                return ResourceManager.GetString("Image_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.jpg.
        /// </summary>
        internal static string Image_Background {
            get {
                return ResourceManager.GetString("Image_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eye_b.png.
        /// </summary>
        internal static string Image_Eye {
            get {
                return ResourceManager.GetString("Image_Eye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eye_none_b.png.
        /// </summary>
        internal static string Image_Eye_None {
            get {
                return ResourceManager.GetString("Image_Eye_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook_g.png.
        /// </summary>
        internal static string Image_Facebook {
            get {
                return ResourceManager.GetString("Image_Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to instagram_g.png.
        /// </summary>
        internal static string Image_Instagram {
            get {
                return ResourceManager.GetString("Image_Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo_w.png.
        /// </summary>
        internal static string Image_Logo {
            get {
                return ResourceManager.GetString("Image_Logo", resourceCulture);
            }
        }
    }
}
