//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mobile.Resources.Strings.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retos.
        /// </summary>
        internal static string Challenges_Title_Label {
            get {
                return ResourceManager.GetString("Challenges_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo salió mal, intenta más tarde..
        /// </summary>
        internal static string General_WebService_UnexpectedResponse {
            get {
                return ResourceManager.GetString("General_WebService_UnexpectedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LogIn_Form_Email_Hint {
            get {
                return ResourceManager.GetString("LogIn_Form_Email_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@example.com.
        /// </summary>
        internal static string LogIn_Form_Email_Placeholder {
            get {
                return ResourceManager.GetString("LogIn_Form_Email_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email es inválido..
        /// </summary>
        internal static string LogIn_Form_Email_Validation_InvalidFormat {
            get {
                return ResourceManager.GetString("LogIn_Form_Email_Validation_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El email es requerido..
        /// </summary>
        internal static string LogIn_Form_Email_Validation_Required {
            get {
                return ResourceManager.GetString("LogIn_Form_Email_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olvidaste tu contraseña?.
        /// </summary>
        internal static string LogIn_Form_ForgottenPassword_Label {
            get {
                return ResourceManager.GetString("LogIn_Form_ForgottenPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string LogIn_Form_Password_Hint {
            get {
                return ResourceManager.GetString("LogIn_Form_Password_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***********.
        /// </summary>
        internal static string LogIn_Form_Password_Placeholder {
            get {
                return ResourceManager.GetString("LogIn_Form_Password_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es inválida..
        /// </summary>
        internal static string LogIn_Form_Password_Validation_InvalidFormat {
            get {
                return ResourceManager.GetString("LogIn_Form_Password_Validation_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña es requerida..
        /// </summary>
        internal static string LogIn_Form_Password_Validation_Required {
            get {
                return ResourceManager.GetString("LogIn_Form_Password_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LogIn_Form_SignIn_Button {
            get {
                return ResourceManager.GetString("LogIn_Form_SignIn_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrarme.
        /// </summary>
        internal static string LogIn_Form_SignUp_Button {
            get {
                return ResourceManager.GetString("LogIn_Form_SignUp_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenido a.
        /// </summary>
        internal static string LogIn_HeadLine_Label {
            get {
                return ResourceManager.GetString("LogIn_HeadLine_Label", resourceCulture);
            }
        }
    }
}
