global using System.Collections.ObjectModel;
global using Acr.UserDialogs;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using MediatR;
global using Mobile.Constants;
global using Mobile.Exceptions;
global using Mobile.Pages;
global using Mobile.Primitives;
